### ISSUE TITLE
1.5.0 crashes when running sample code

### ISSUE THREAD

**Issue by luismartingarcia** [giampaolo/pyftpdlib#355]
Hi,

When I try to run the following code:

```
    authorizer = DummyAuthorizer()
    authorizer.add_user("user", "12345", ".", perm="elradfmw")
    authorizer.add_anonymous(".")
    handler = FTPHandler
    handler.authorizer = authorizer
    server = FTPServer(("127.0.0.1", 21), handler)
    server.serve_forever()
```

I get an exception:

```
$ ./aci-export.py
[I 2015-10-28 15:17:30] >>> starting FTP server on 127.0.0.1:21, pid=6584 <<<
[I 2015-10-28 15:17:30] concurrency model: async
[I 2015-10-28 15:17:30] masquerade (NAT) address: None
[I 2015-10-28 15:17:30] passive ports: None
Traceback (most recent call last):
  File "./aci-export.py", line 56, in <module>
    server.serve_forever()
  File "/usr/lib/python2.7/site-packages/pyftpdlib-1.5.0-py2.7.egg/pyftpdlib/servers.py", line 200, in serve_forever
    self._log_start()
  File "/usr/lib/python2.7/site-packages/pyftpdlib-1.5.0-py2.7.egg/pyftpdlib/servers.py", line 170, in _log_start
    logger.debug("handler: %r", get_fqname(self.handler))
  File "/usr/lib/python2.7/site-packages/pyftpdlib-1.5.0-py2.7.egg/pyftpdlib/servers.py", line 132, in get_fqname
    return obj.__module__ + "." + obj.__class__.__name__
AttributeError: class FTPHandler has no attribute '__class__'
```

This is recent. The same code works fine with pyftpdlib==1.4.1, but not with the latest pyftpdlib==1.5.0 from the master branch.

I'm running this on top of Cygwin 64-bit on  a Windows 7 box.

Thanks!

Luis.

**Comment by giampaolo** [comment]
Ouch! My bad sorry. It's fixed now.
